# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-
# stub: redis-call 1.0.2 ruby lib

Gem::Specification.new do |s|
  s.name = "redis-call"
  s.version = "1.0.2"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.require_paths = ["lib"]
  s.authors = ["Stanislav Senotrusov"]
  s.date = "2017-04-23"
  s.email = "stan@senotrusov.com"
  s.extra_rdoc_files = [
    "LICENSE",
    "README.md"
  ]
  s.files = [
    "CONTRIBUTING.md",
    "ISSUE_TEMPLATE.md",
    "LICENSE",
    "PULL_REQUEST_TEMPLATE.md",
    "README.md",
    "Rakefile",
    "VERSION",
    "lib/redis-call.rb",
    "lib/redis-call/railtie.rb",
    "lib/redis-call/redis_call.rb",
    "lib/redis-call/redis_queue.rb",
    "redis-call.gemspec"
  ]
  s.homepage = "https://github.com/senotrusov/redis-call"
  s.licenses = ["Apache-2.0"]
  s.rubygems_version = "2.5.1"
  s.summary = "Redis access library for Ruby: threads, handy key names, transactions and queues"

  if s.respond_to? :specification_version then
    s.specification_version = 4

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<hiredis>, [">= 0"])
      s.add_runtime_dependency(%q<yajl-ruby>, [">= 0"])
    else
      s.add_dependency(%q<hiredis>, [">= 0"])
      s.add_dependency(%q<yajl-ruby>, [">= 0"])
    end
  else
    s.add_dependency(%q<hiredis>, [">= 0"])
    s.add_dependency(%q<yajl-ruby>, [">= 0"])
  end
end

